In [59]:
import pandas as pd
import numpy as np 
from pymongo import MongoClient

__Подключение к MONGO DB, выгрузка датасета__

In [60]:
client = MongoClient('localhost', 27017)

# Connect to our database
db = client['finviz_spider']

# Fetch our series collection
series_collection_ticker = db['ticker']

In [61]:
temp = db.finviz.find({})

In [62]:
temp

In [63]:
df =  pd.DataFrame(list(temp))

In [64]:
df

,_id,ticker,info_features,info_params,info_industry
0,62064f6cedaeb4f2c79cf916,[AAP],"[Index, P/E, EPS (ttm), Insider Own, Shs Outst...","[S&P 500, 22.54, 9.88, 0.10%, 62.85M, -4.20%, ...",[Consumer Cyclical]
1,62064f6cedaeb4f2c79cf917,[AAQC],"[Index, P/E, EPS (ttm), Insider Own, Shs Outst...","[-, -, -, -, 40.00M, -0.10%, 388.00M, -, -, -,...",[Financial]
2,62064f6cedaeb4f2c79cf918,[AAOI],"[Index, P/E, EPS (ttm), Insider Own, Shs Outst...","[-, -, -2.05, 6.40%, 27.10M, 2.08%, 104.58M, -...",[Technology]
3,62064f6cedaeb4f2c79cf919,[AAPL],"[Index, P/E, EPS (ttm), Insider Own, Shs Outst...","[DJIA S&P500, 28.58, 6.02, 0.07%, 16.39B, -0.4...",[Technology]
4,62064f6cedaeb4f2c79cf91a,[AAON],"[Index, P/E, EPS (ttm), Insider Own, Shs Outst...","[-, 43.79, 1.33, 16.60%, 52.42M, -4.43%, 3.12B...",[Industrials]
...,...,...,...,...,...
8555,62065156edaeb4f2c79d1a81,[ZNTEU],"[Index, P/E, EPS (ttm), Insider Own, Shs Outst...","[-, -, -, -, -, -1.14%, -, -, -, -, 16.26M, -1...",[Financial]
8556,62065156edaeb4f2c79d1a82,[ZIG],"[Index, P/E, EPS (ttm), Insider Own, Shs Outst...","[-, -, -, -, -, -0.46%, -, -, -, -, -, -6.57%,...",[Financial]
8557,62065156edaeb4f2c79d1a83,[ZHDG],"[Index, P/E, EPS (ttm), Insider Own, Shs Outst...","[-, -, -, -, -, -0.10%, -, -, -, -, -, -3.90%,...",[Financial]
8558,62065156edaeb4f2c79d1a84,[ZH],"[Index, P/E, EPS (ttm), Insider Own, Shs Outst...","[-, -, -0.38, -, 561.50M, 8.99%, 2.29B, -, -1....",[Communication Services]
8559,62065156edaeb4f2c79d1a85,[ZI],"[Index, P/E, EPS (ttm), Insider Own, Shs Outst...","[-, 837.50, 0.07, 12.90%, 263.29M, 15.96%, 21....",[Technology]

In [65]:
df = df.drop('_id', axis=1)

In [66]:
#добавим к нашим акциям номера id
id_share = np.arange(1, 8561)

In [67]:
df['id_share'] = id_share

In [68]:
df.head()

,ticker,info_features,info_params,info_industry,id_share
0,[AAP],"[Index, P/E, EPS (ttm), Insider Own, Shs Outst...","[S&P 500, 22.54, 9.88, 0.10%, 62.85M, -4.20%, ...",[Consumer Cyclical],1
1,[AAQC],"[Index, P/E, EPS (ttm), Insider Own, Shs Outst...","[-, -, -, -, 40.00M, -0.10%, 388.00M, -, -, -,...",[Financial],2
2,[AAOI],"[Index, P/E, EPS (ttm), Insider Own, Shs Outst...","[-, -, -2.05, 6.40%, 27.10M, 2.08%, 104.58M, -...",[Technology],3
3,[AAPL],"[Index, P/E, EPS (ttm), Insider Own, Shs Outst...","[DJIA S&P500, 28.58, 6.02, 0.07%, 16.39B, -0.4...",[Technology],4
4,[AAON],"[Index, P/E, EPS (ttm), Insider Own, Shs Outst...","[-, 43.79, 1.33, 16.60%, 52.42M, -4.43%, 3.12B...",[Industrials],5

__Преобразуем столбцы ticker, info_industry__

In [69]:
list_of_tickers = df.ticker.to_list()
list_of_industries = df.info_industry.to_list()

In [70]:
list_of_tickers = np.array(list_of_tickers)
list_of_tickers = list_of_tickers.flatten()

In [71]:
list_of_industries = np.array(list_of_industries)
list_of_industries = list_of_industries.flatten()

In [72]:
df['ticker'] = list_of_tickers
df['industry'] = list_of_industries

In [73]:
df = df.drop('info_industry', axis=1)

__Преобразование features и parameters__

In [74]:
df.head()

,ticker,info_features,info_params,id_share,industry
0,AAP,"[Index, P/E, EPS (ttm), Insider Own, Shs Outst...","[S&P 500, 22.54, 9.88, 0.10%, 62.85M, -4.20%, ...",1,Consumer Cyclical
1,AAQC,"[Index, P/E, EPS (ttm), Insider Own, Shs Outst...","[-, -, -, -, 40.00M, -0.10%, 388.00M, -, -, -,...",2,Financial
2,AAOI,"[Index, P/E, EPS (ttm), Insider Own, Shs Outst...","[-, -, -2.05, 6.40%, 27.10M, 2.08%, 104.58M, -...",3,Technology
3,AAPL,"[Index, P/E, EPS (ttm), Insider Own, Shs Outst...","[DJIA S&P500, 28.58, 6.02, 0.07%, 16.39B, -0.4...",4,Technology
4,AAON,"[Index, P/E, EPS (ttm), Insider Own, Shs Outst...","[-, 43.79, 1.33, 16.60%, 52.42M, -4.43%, 3.12B...",5,Industrials

In [75]:
list_of_features = df['info_features'][0]

In [76]:
for j in range(len(list_of_features)): 
    for i in range(df.shape[0]): 
        df.loc[i, list_of_features[j]] = df['info_params'][i][j]

In [77]:
df = df.drop(['info_features', 'info_params'], axis=1)

In [78]:
df

,ticker,id_share,industry,Index,P/E,EPS (ttm),Insider Own,Shs Outstand,Perf Week,Market Cap,...,Earnings,Payout,Avg Volume,Price,Recom,SMA20,SMA50,SMA200,Volume,Change
0,AAP,1,Consumer Cyclical,S&P 500,22.54,9.88,0.10%,62.85M,-4.20%,14.23B,...,Feb 14 AMC,25.10%,679.29K,222.73,2.20,-3.96%,-4.48%,3.16%,"1,905,138",-4.07%
1,AAQC,2,Financial,-,-,-,-,40.00M,-0.10%,388.00M,...,-,-,55.94K,9.70,-,-0.09%,-0.17%,-0.09%,118,-0.21%
2,AAOI,3,Technology,-,-,-2.05,6.40%,27.10M,2.08%,104.58M,...,Feb 24 AMC,-,506.56K,3.93,2.70,-1.74%,-18.82%,-42.16%,"260,131",-2.96%
3,AAPL,4,Technology,DJIA S&P500,28.58,6.02,0.07%,16.39B,-0.45%,2817.21B,...,Jan 27 AMC,14.20%,101.62M,172.12,1.80,1.62%,0.08%,14.95%,"90,865,896",-2.36%
4,AAON,5,Industrials,-,43.79,1.33,16.60%,52.42M,-4.43%,3.12B,...,Nov 04 AMC,27.80%,244.13K,58.42,3.00,-9.81%,-19.95%,-14.75%,"557,572",-2.34%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8555,ZNTEU,8556,Financial,-,-,-,-,-,-1.14%,-,...,-,-,3.23K,10.41,-,-2.06%,-1.59%,-5.84%,271,-2.80%
8556,ZIG,8557,Financial,-,-,-,-,-,-0.46%,-,...,-,-,9.16K,29.30,-,-1.14%,-3.75%,2.30%,"3,588",-2.10%
8557,ZHDG,8558,Financial,-,-,-,-,-,-0.10%,-,...,-,-,34.95K,19.94,-,-0.67%,-2.97%,-2.33%,"18,703",-1.43%
8558,ZH,8559,Communication Services,-,-,-0.38,-,561.50M,8.99%,2.29B,...,Nov 22 BMO,-,2.29M,4.12,1.90,-0.94%,-19.71%,-51.57%,"1,936,984",1.98%
8559,ZI,8560,Technology,-,837.50,0.07,12.90%,263.29M,15.96%,21.39B,...,Feb 15 AMC,0.00%,4.53M,56.95,1.80,12.46%,-0.18%,-1.83%,"5,468,203",2.04%

__Обработка переменных датасета__

In [79]:
columns = df.columns.to_list()

In [80]:
#columns

In [81]:
number_columns = ['P/E', 'Forward P/E', 'PEG', 'P/S', 'P/B', 'P/C', 'P/FCF', 'Current Ratio', 'Quick Ratio',
                 'Book/sh', 'Cash/sh', 'Dividend', 'Debt/Eq', 'LT Debt/Eq', 'EPS (ttm)', 'EPS next Q', 
                 'Short Ratio', 'Target Price', 'Beta', 'ATR', 'RSI (14)', 'Rel Volume', 'Prev Close', 'Price', 'Recom', 'Employees']

In [82]:
len(number_columns)

26

In [83]:
percent_columns = ['SMA20', 'Insider Own', 'Perf Week', 'Insider Trans', 'Perf Month', 'Inst Own', 'Short Float', 
                  'Perf Quarter', 'EPS this Y', 'Inst Trans', 'Perf Half Y', 'EPS next Y', 'EPS next 5Y', 'EPS past 5Y',
                  'ROA', 'ROE', 'ROI', 'Gross Margin', 'Oper. Margin', 'EPS Q/Q', 'Sales Q/Q', 'Dividend %', 'Sales past 5Y', 
                  'SMA50', 'SMA200',  'Payout', 'Profit Margin', '52W High', '52W Low', 'Perf YTD', 'Perf Year', 'Change']

In [84]:
len(percent_columns)

32

In [85]:
range_columns = ['52W Range', 'Volatility']

In [86]:
#возможно стоит оставить без обработки
word_columns = ['Index', 'Optionable', 'Shortable', 'Earnings']

In [87]:
short_word_columns = [ 'Market Cap', 'Income', 'Sales', 'Shs Outstand','Shs Float', 'Avg Volume']

In [88]:
volume_column = ['Volume']

In [89]:
assert(len(number_columns) + len(percent_columns) + len(range_columns) + len(word_columns) + len (short_word_columns) +  
       len(volume_column) == 71)

__Обработка столбцов с %__

In [90]:
def percent_column_treatment(name_column, X):
    
    X[name_column] = X[name_column].map(lambda x: x[:-1])
    X[name_column] = X[name_column].replace('', float('nan'))
    X[name_column] = X[name_column].astype(float)
    
    return X

In [91]:
for feature in percent_columns: 
    df = percent_column_treatment(feature, df)

In [93]:
df.head()

,ticker,id_share,industry,Index,P/E,EPS (ttm),Insider Own,Shs Outstand,Perf Week,Market Cap,...,Earnings,Payout,Avg Volume,Price,Recom,SMA20,SMA50,SMA200,Volume,Change
0,AAP,1,Consumer Cyclical,S&P 500,22.54,9.88,0.10,62.85M,-4.20,14.23B,...,Feb 14 AMC,25.1,679.29K,222.73,2.20,-3.96,-4.48,3.16,"1,905,138",-4.07
1,AAQC,2,Financial,-,-,-,NaN,40.00M,-0.10,388.00M,...,-,NaN,55.94K,9.70,-,-0.09,-0.17,-0.09,118,-0.21
2,AAOI,3,Technology,-,-,-2.05,6.40,27.10M,2.08,104.58M,...,Feb 24 AMC,NaN,506.56K,3.93,2.70,-1.74,-18.82,-42.16,"260,131",-2.96
3,AAPL,4,Technology,DJIA S&P500,28.58,6.02,0.07,16.39B,-0.45,2817.21B,...,Jan 27 AMC,14.2,101.62M,172.12,1.80,1.62,0.08,14.95,"90,865,896",-2.36
4,AAON,5,Industrials,-,43.79,1.33,16.60,52.42M,-4.43,3.12B,...,Nov 04 AMC,27.8,244.13K,58.42,3.00,-9.81,-19.95,-14.75,"557,572",-2.34

__Обработка числовых столбцов__

In [94]:
def number_column_treatment(name_column, X):
    
    X[name_column] = X[name_column].replace('-', float('nan'))
    X[name_column] = X[name_column].astype(float)
    
    return X

In [95]:
for feat in number_columns: 
    df = number_column_treatment(feat, df)

In [97]:
df

,ticker,id_share,industry,Index,P/E,EPS (ttm),Insider Own,Shs Outstand,Perf Week,Market Cap,...,Earnings,Payout,Avg Volume,Price,Recom,SMA20,SMA50,SMA200,Volume,Change
0,AAP,1,Consumer Cyclical,S&P 500,22.54,9.88,0.10,62.85M,-4.20,14.23B,...,Feb 14 AMC,25.1,679.29K,222.73,2.2,-3.96,-4.48,3.16,"1,905,138",-4.07
1,AAQC,2,Financial,-,NaN,NaN,NaN,40.00M,-0.10,388.00M,...,-,NaN,55.94K,9.70,NaN,-0.09,-0.17,-0.09,118,-0.21
2,AAOI,3,Technology,-,NaN,-2.05,6.40,27.10M,2.08,104.58M,...,Feb 24 AMC,NaN,506.56K,3.93,2.7,-1.74,-18.82,-42.16,"260,131",-2.96
3,AAPL,4,Technology,DJIA S&P500,28.58,6.02,0.07,16.39B,-0.45,2817.21B,...,Jan 27 AMC,14.2,101.62M,172.12,1.8,1.62,0.08,14.95,"90,865,896",-2.36
4,AAON,5,Industrials,-,43.79,1.33,16.60,52.42M,-4.43,3.12B,...,Nov 04 AMC,27.8,244.13K,58.42,3.0,-9.81,-19.95,-14.75,"557,572",-2.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8555,ZNTEU,8556,Financial,-,NaN,NaN,NaN,-,-1.14,-,...,-,NaN,3.23K,10.41,NaN,-2.06,-1.59,-5.84,271,-2.80
8556,ZIG,8557,Financial,-,NaN,NaN,NaN,-,-0.46,-,...,-,NaN,9.16K,29.30,NaN,-1.14,-3.75,2.30,"3,588",-2.10
8557,ZHDG,8558,Financial,-,NaN,NaN,NaN,-,-0.10,-,...,-,NaN,34.95K,19.94,NaN,-0.67,-2.97,-2.33,"18,703",-1.43
8558,ZH,8559,Communication Services,-,NaN,-0.38,NaN,561.50M,8.99,2.29B,...,Nov 22 BMO,NaN,2.29M,4.12,1.9,-0.94,-19.71,-51.57,"1,936,984",1.98
8559,ZI,8560,Technology,-,837.50,0.07,12.90,263.29M,15.96,21.39B,...,Feb 15 AMC,0.0,4.53M,56.95,1.8,12.46,-0.18,-1.83,"5,468,203",2.04

__Обработка short_word_columns__

In [98]:
def short_word_columns_treatment(name_column, X):
    list_column = X[name_column].to_list()
    f=[]
    for i in range(len(list_column)): 
        spam = list_column[i]
        if spam[-1] == 'B': 
            spam = float(list_column[i][:-1])*1*10**12
        elif spam[-1] == 'M': 
            spam = float(list_column[i][:-1])*1*10**6
        elif spam[-1] == 'K':
            spam = float(list_column[i][:-1])*1*10**3
        elif spam == '-':
            spam = float('nan')
        f.append(spam)
    X[name_column + '_full_count'] = f
    X = X.drop(name_column, axis=1)
    return X

In [99]:
for word_feat in short_word_columns: 
    df = short_word_columns_treatment(word_feat, df)

In [100]:
df

,ticker,id_share,industry,Index,P/E,EPS (ttm),Insider Own,Perf Week,Forward P/E,EPS next Y,...,SMA50,SMA200,Volume,Change,Market Cap_full_count,Income_full_count,Sales_full_count,Shs Outstand_full_count,Shs Float_full_count,Avg Volume_full_count
0,AAP,1,Consumer Cyclical,S&P 500,22.54,9.88,0.10,-4.20,16.78,11.37,...,-4.48,3.16,"1,905,138",-4.07,1.423000e+13,6.464000e+08,1.097000e+13,6.285000e+07,6.208000e+07,679290.0
1,AAQC,2,Financial,-,NaN,NaN,NaN,-0.10,NaN,NaN,...,-0.17,-0.09,118,-0.21,3.880000e+08,NaN,NaN,4.000000e+07,NaN,55940.0
2,AAOI,3,Technology,-,NaN,-2.05,6.40,2.08,NaN,15.40,...,-18.82,-42.16,"260,131",-2.96,1.045800e+08,-5.310000e+07,2.095000e+08,2.710000e+07,2.539000e+07,506560.0
3,AAPL,4,Technology,DJIA S&P500,28.58,6.02,0.07,-0.45,26.29,6.42,...,0.08,14.95,"90,865,896",-2.36,2.817210e+15,1.005600e+14,3.783200e+14,1.639000e+13,1.631000e+13,101620000.0
4,AAON,5,Industrials,-,43.79,1.33,16.60,-4.43,34.57,34.88,...,-19.95,-14.75,"557,572",-2.34,3.120000e+12,7.150000e+07,5.149000e+08,5.242000e+07,4.156000e+07,244130.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8555,ZNTEU,8556,Financial,-,NaN,NaN,NaN,-1.14,NaN,NaN,...,-1.59,-5.84,271,-2.80,NaN,NaN,NaN,NaN,1.626000e+07,3230.0
8556,ZIG,8557,Financial,-,NaN,NaN,NaN,-0.46,NaN,NaN,...,-3.75,2.30,"3,588",-2.10,NaN,NaN,NaN,NaN,NaN,9160.0
8557,ZHDG,8558,Financial,-,NaN,NaN,NaN,-0.10,NaN,NaN,...,-2.97,-2.33,"18,703",-1.43,NaN,NaN,NaN,NaN,NaN,34950.0
8558,ZH,8559,Communication Services,-,NaN,-0.38,NaN,8.99,NaN,NaN,...,-19.71,-51.57,"1,936,984",1.98,2.290000e+12,-2.116000e+08,3.867000e+08,5.615000e+08,5.499300e+08,2290000.0
8559,ZI,8560,Technology,-,837.50,0.07,12.90,15.96,83.02,32.95,...,-0.18,-1.83,"5,468,203",2.04,2.139000e+13,-2.600000e+06,6.646000e+08,2.632900e+08,2.107000e+08,4530000.0

__Обработка оставшихся специфических данных__

_Volume_

In [103]:
df['Volume'] = df['Volume'].map(lambda x: x.replace(',', ''))

In [104]:
df['Volume'] = df['Volume'].astype(float)

_Range_

In [107]:
list_of_range = df['52W Range'].to_list()

In [108]:
f_low = []
f_high = []
for i in range(len(list_of_range)): 
    spam = list_of_range[i].split()
    spam_low = spam[0]
    spam_high = spam[2]
    f_low.append(spam_low)
    f_high.append(spam_high)

In [109]:
df['52_w_range_low'] = f_low
df['52_w_range_high'] = f_high

In [110]:
df['52_w_range_low'] = df['52_w_range_low'].replace('-', float('nan'))

In [111]:
df['52_w_range_high'] = df['52_w_range_high'].replace('-', float('nan'))

In [112]:
#type_float

In [113]:
df['52_w_range_low'] = df['52_w_range_low'].astype(float)

In [114]:
df['52_w_range_high'] = df['52_w_range_high'].astype(float)

In [115]:
df = df.drop('52W Range', axis=1)

_Volatility_

In [116]:
df['Volatility'].unique()

array(['2.73% 2.73%', '0.16% 0.18%', '5.01% 5.43%', ..., '1.16% 1.29%',
       '6.33% 7.85%', '6.45% 6.79%'], dtype=object)

In [117]:
list_of_volatility = df['Volatility'].to_list()

In [118]:
f_low = []
f_high = []
for i in range(len(list_of_volatility)): 
    spam = list_of_volatility[i].split()
    spam_low = spam[0]
    spam_high = spam[1]
    f_low.append(spam_low)
    f_high.append(spam_high)

In [119]:
df['Volatility_low_%'] = [i[:-1] for i in f_low]
df['Volatility_high_%'] = [i[:-1] for i in f_high]

In [120]:
df['Volatility_low_%'] = df['Volatility_low_%'].replace('', float('nan'))
df['Volatility_high_%'] = df['Volatility_high_%'].replace('', float('nan'))

In [121]:
df['Volatility_low_%'] = df['Volatility_low_%'].astype(float)
df['Volatility_high_%'] = df['Volatility_high_%'].astype(float)

In [122]:
df['Volatility_low_%'].unique()

array([ 2.73,  0.16,  5.01, ..., 13.59, 14.66, 25.53])

In [123]:
df = df.drop('Volatility', axis=1)

In [124]:
#сохраним обработанный датасет для дальнейшего EDA.

In [125]:
file_name = 'finviz_shares.csv'

In [126]:
df.to_csv(file_name, encoding='utf-8', index=False)